apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
spec:
  template:
    spec:
      containers:
        - name: argocd-image-updater
          args: ['--loglevel', 'debug', '--interval', '10s']
          volumeMounts:
            - name: resolv-conf
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
      volumes:
      - name: resolv-conf
        configMap:
          name: resolv-conf
          items:
            - key: resolv.conf
              path: resolv.conf
