apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
- ../base
- ../../security/zap

patches:
- path: patches/argo-server-deployment.yaml
- path: patches/argo-server-service.yaml
# - patch: |-
#     - op: replace
#       path: /spec/type
#       value: LoadBalancer
#   target:
#     group: ""
#     version: v1
#     kind: Service
#     name: argo-server
