---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-and-push
spec:
  templates:
  - name: build
    inputs:
      parameters:
      - name: repo_url
      - name: repo_ref
      - name: repo_commit_id
      - name: container_image
      - name: container_tag
    # outputs:
    #   parameters:
    #   - name: container_image
    #     value: "{{inputs.parameters.container_image}}"
    #   - name: container_tag
    #     value: "{{inputs.parameters.container_tag}}"
    container:
      image: gcr.io/kaniko-project/executor:debug
      args:
      - --context={{inputs.parameters.repo_url}} #{{inputs.parameters.repo_ref}}#{{inputs.parameters.repo_commit_id}}
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
      - --cache-run-layers
      - --cache-copy-layers
      - --cache=true
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker
    volumes:
    - name: regcred
      secret:
        secretName: regcred
        items:
        - key: .dockerconfigjson
          path: config.json
