apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: ci-cd-template
spec:
  entrypoint: build
  templates:
  - name: sleep
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo 'Waiting for cluster to sync...'
        sleep 5
        echo 'Done'
  - name: zap-scan
    volumes:
    - name: zap-reports
      emptyDir: {}
    - name: zap-config
      configMap:
        name: zap-config
    container:
      image: softwaresecurityproject/zap-stable
      # command: [zap-baseline.py]
      # args: [-t, 'http://juice-shop-service.juice-shop-test.svc.cluster.local:3000', -g, 'gen.conf', -r, 'testreport.html', -I] # <CHANGE_ME>
      command: [ls]
      volumeMounts:
      - name: zap-reports
        mountPath: /zap/wrk/
      - name: zap-config
        mountPath: /zap
  - name: build
    dag:
      tasks:
      # - name: build
      #   # dependencies: [sast, lint, deprecations]
      #   templateRef:
      #     name: build-and-push
      #     template: build
      #     clusterScope: true
      #   arguments:
      #     parameters:
      #     - name: repo_url
      #       value: git://github.com/iurimihai/juice-shop.git
      #     - name: repo_ref
      #       value: refs/heads/main
      #     - name: repo_commit_id
      #       value: HEAD
      #     - name: container_image
      #       value: iurimihai/juice-shop-test
      #     - name: container_tag
      #       value: 1.1.0
      - name: deploy-staging
        # dependencies: [build]
        template: sleep
      - name: zap-baseline-scan
        dependencies: [deploy-staging]
        template: zap-scan
      - name: deploy-prod
        dependencies: [zap-baseline-scan]
        templateRef:
          name: promote
          template: promote
          clusterScope: true
        arguments:
          parameters:
          - name: test_container_image
            value: iurimihai/juice-shop-test
          - name: test_container_tag
            value: 1.1.1
          - name: prod_container_image
            value: iurimihai/juice-shop-prod
          - name: prod_container_tag
            value: 1.1.0
