apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: ci-cd-template
spec:
  entrypoint: build
  templates:
  - name: build
    dag:
      tasks:
      - name: build
        # dependencies: [sast, lint, deprecations]
        templateRef:
          name: build-and-push
          template: build
          clusterScope: true
        arguments:
          parameters:
          - name: repo_url
            value: git://github.com/iurimihai/juice-shop.git
          - name: repo_ref
            value: refs/heads/main
          - name: repo_commit_id
            value: HEAD
          - name: container_image
            value: iurimihai/juice-shop-test
          - name: container_tag
            value: 1.0.0
      - name: deploy-staging
        dependencies: [build]
        script:
          image: alpine:latest
          command: [sh, '-c']
          source: |
            sleep 180
      # - name: wait-for-cluster-sync
      #   dependencies: [deploy-staging]
      #   script:
      #     image: alpine/latest
      #     command: [sh, '-c']
      #     source: |
      #       sleep 120
      - name: deploy-prod
        dependencies: [deploy-staging]
        templateRef:
          name: promote
          template: promote
          clusterScope: true
        arguments:
          parameters:
          - name: test_container_image
            value: iurimihai/juice-shop-test
          - name: test_container_tag
            value: 1.0.0
          - name: prod_container_image
            value: iurimihai/juice-shop-prod
          - name: prod_container_tag
            value: 1.0.0
