apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: ci-cd-template
spec:
  entrypoint: build
  arguments:
    parameters:
    - name: repo_url
      value: git://github.com/iurimihai/juice-shop.git
    - name: repo_ref
      value: master
    - name: repo_commit_id
      value: HEAD
    - name: container_image
      value: iurimihai/juice-shop-test
    - name: test_container_tag
      value: test
    - name: prod_container_tag
      value: latest
  templates:
  - name: sleep
    script:
      image: alpine:latest
      command: [sh]
      source: |
        echo 'Waiting for cluster to sync...'
        sleep 5
        echo 'Done'
  - name: zap-scan
    volumes:
    - name: zap-reports
      emptyDir: {}
    - name: zap-config
      configMap:
        name: zap-config
    container:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      image: zaproxy/zap-stable
      # command: ["ls"]
      # args: ["-l", "/wrk/", "/zap-config/", '/zap/']
      # args: [-t, 'http://juice-shop-service.juice-shop-test.svc.cluster.local:3000', -g, 'gen.conf', -r, 'testreport.html', -I] # <CHANGE_ME>
      command: [zap.sh]
      args: [-cmd, -autorun, /zap-config/zap.yaml]
      volumeMounts:
      - name: zap-reports
        mountPath: /wrk/
      - name: zap-config
        mountPath: /zap-config/
  - name: build
    dag:
      tasks:
      # - name: build
      #   template: zap-scan
      - name: build
        # dependencies: [sast, lint, deprecations]
        templateRef:
          name: build-and-push
          template: build
          clusterScope: true
        arguments:
          parameters:
          - name: repo_url
            value: "{{workflow.parameters.repo_url}}"
          - name: repo_ref
            value: "{{workflow.parameters.repo_ref}}"
          - name: repo_commit_id
            value: "{{workflow.parameters.repo_commit_id}}"
          - name: container_image
            value: "{{workflow.parameters.container_image}}"
          - name: container_tag
            value: "{{workflow.parameters.test_container_tag}}"
      - name: deploy-staging
        dependencies: [build]
        template: sleep
      - name: zap-baseline-scan
        dependencies: [deploy-staging]
        template: zap-scan
      - name: deploy-prod
        dependencies: [zap-baseline-scan]
        templateRef:
          name: promote
          template: promote
          clusterScope: true
        arguments:
          parameters:
          - name: container_image
            value: "{{workflow.parameters.container_image}}"
          - name: test_container_tag
            value: "{{workflow.parameters.test_container_tag}}"
          - name: prod_container_tag
            value: "{{workflow.parameters.prod_container_tag}}"
