---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: promote
spec:
  templates:
  - name: promote
    inputs:
      parameters:
      - name: test_container_image
      - name: test_container_tag
      - name: prod_container_image
      - name: prod_container_tag
    script:
      image: gcr.io/kaniko-project/executor:debug
      command: [sh]
      source: |
        echo "FROM {{inputs.parameters.test_container_image}}:{{inputs.parameters.test_container_tag}}" | \
          /kaniko/executor --dockerfile /dev/stdin --destination {{inputs.parameters.prod_container_image}}:{{inputs.parameters.prod_container_tag}}
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker
    volumes:
    - name: regcred
      secret:
        secretName: regcred
        items:
        - key: .dockerconfigjson
          path: config.json
