---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: promote
spec:
  templates:
  - name: promote
    inputs:
      parameters:
      - name: test_container_image
        value: iurimihai/juice-shop-test
      - name: test_container_tag
        value: 1.0.0
      - name: prod_container_image
        value: iurimihai/juice-shop-prod
      - name: prod_container_tag
        value: 1.0.0
    script:
      image: gcr.io/kaniko-project/executor:debug
      command: [sh]
      source: |
        echo "FROM {{inputs.parameters.test_container_image}}:{{inputs.parameters.test_container_tag}}" | \
          kaniko/executor --dockerfile /dev/stdin --destination {{inputs.parameters.prod_container_image}}:{{inputs.parameters.prod_container_tag}}
      volumeMounts:
        - name: regcred
          mountPath: /kaniko/.docker
    volumes:
    - name: regcred
      secret:
        secretName: regcred
        items:
        - key: .dockerconfigjson
          path: config.json
