
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    # - name: test-dep
    #   eventSourceName: webhook
    #   eventName: build
    - name: github-event
      eventSourceName: github
      eventName: github-event
  triggers:
    - template:
        name: ci-cd-workflow-trigger
        k8s:
          # group: argoproj.io
          # version: v1alpha1
          # operation: submit
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-cd-
                namespace: argo
              spec:
                entrypoint: build
                workflowTemplateRef:
                  name: ci-cd-template
                  clusterScope: true
                arguments:
                  parameters:
                  - name: repo_url
                    value: git://github.com/iurimihai/juice-shop.git
                  - name: repo_ref
                    value: master
                  - name: repo_commit_id
                    value: HEAD
                  - name: test_container_image
                    value: iurimihai/juice-shop-test
                  - name: test_container_tag
                    value: test
                  - name: prod_container_image
                    value: iurimihai/juice-shop-prod
                  - name: prod_container_tag
                    value: latest
          parameters:
          - src:
              dependencyName: github-event
              dataKey: body.repository.git_url
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: github-event
              dataKey: body.ref
            dest: spec.arguments.parameters.1.value
          - src:
              dependencyName: github-event
              dataKey: body.before
            dest: spec.arguments.parameters.4.value
          - src:
              dependencyName: github-event
              dataKey: body.after
            dest: spec.arguments.parameters.6.value
