apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: http
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: github-eventsource-svc
           port:
             number: 12000
    host: gh-event.iurimihai.dev

