---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCzTi9OO1LRkA3P1thdsRBZK+p4yPeMX2RGguTI/TZSWf909Ir7FChDWJ8ihaxwMazA+axXZK04fC6qV2smbuyYNTjjrEioTXv3zvzKwwMtkwjHF2TlRR1iY0FA0L/rk4CrPlHbAedacC5kbQOuS3dlWN07T1bjTipt1sKK2oL6asNVdBhgjaur7D4M79CcqrRl/I07WWX1apgR2wXNQgKYB0/q3ZeoIgNmy1NCAy4WzokvPTTNUeKwQmRW+zaGPsqDWxoMfWfV0hsizikL+rp0CU6pERlD+G+ZaucUJJdrpa2FGNt4IGMqWVYYcda92P9wTXqEDJrB5NSaWaLocjfdaE8Bi6RscqXJnlYxfte95j2ld4tBiGoG/luhzjcaFQDPhg0feSWEaM+cE0T8pgkU/aKLZJ1B13Deo2Sb9sX+VVnoprR+hV6Kfj3BbbTMEdsXRTCEsHQoAGNGkZQZ/b+89Yq/9zJsFWIE+vu8itD/WheDJFN6eXhCaSAt34EwzXgTJNo+Mnqg/aXCrpxTVWqbWn8aY4ar2TnR7loMNANTQJ5cca/MbhtS2+OmkDKtZWfFjQS/13c/tN0eM6CC/0Tcccxz92/OIdISxA8gVvcagAVWzUpQ8fylmHUxmH4FxPH1g0XGO+oGesnUpYYjvcBgygeS1yuGA87Xd6WqygBmpdSDSsPAXajGP2uV8N8YXmR+AtQ1Bw3Uh9lS3YF7jOnYdIXqAPu1/CX16XLJhvr8DQPnc/ecrK6L
    username: AgCtm/4Aozxl8yJoQF4JhwayAFfR2EBHgFqD8XCwnqKvPURcP6+y7gFTk5DC1jrZ3G+jQMcOrSQ55auOTfzsnlHsrQ7j0itNARxh2VvZwtO2jempR7GZIecTUoIf8rN7Z1tHH+zbyBT8bqjM8nEAba/JGBCCFViWtQSP7fzM8vxWYbPNRwi3IyvQB+OliuPIg9z8bynWh0yprKPBka7flODhLdCC2adP60MfxAqgC91lM6NK2WM42WmJSjPI679oV9lar2d7/dihuPKxpQmEMwwsMU2Nl1Fbb3HVtFfFO74ZXvUlmTF7+Gjzyr5O5xR1MkfsmJnB4aOgCTqliYGiQkXqvLe0lXuDDmiMT4c+i7wlLl5w21NcuoI1BSEqZuK24jJm7gCMBBs0oI2B88KqfVbcQk3sSTC3mnxfN3N966QEAPrsCv/2gJ10ESP4B0cOKs2Oz28V7xlY82QPKLIuWob2sbKvakIr8HBoGLExGoHlxKRazOwGSHboulNF+nE4pC2wel/b1gh0pjWTrZamKjRoMibew/MsQjRnZwoPsUSClAePgX9EubJKpFip9x8EUf1nlPCEcIrgddToPkeFl6YEAZ2uQGVaS46V983cv+6ykMp1/f9V+RnNxKS7oRwKMZsyt2AmC9MtFv2kPIxDa7T5mAfdqwQiOOt3zdh4M4ri9QtE9iPnLQbBjToBVOmohAhKkmnS7BM01qU=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
