---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    password: AgB7YQLewH1X1BGlClxWsULkK2I2Jn9FoVlqd2elA5oa3PXCzMDAQQJsKfZHOObCyNN/QcMTC/4xHGbytqBSWh6CytNSaOABZNFqnTd5C/VfF0MuJ0cADnS0WkJ4ichWghfiXARH0C90uj//w0+NGRhKUtL8lnY+TNT8JwhY1BGwftl8zDbf4swo8AwOCTSDtR0WL0PrlS0nwtatldaJWaNWR/gOX8m9m38x7cBGwhxa3NH3QfCv/nUMHsAKhAEsbJEvRT5B8WKdr3rAVji+wtLmWCiB+GliYOftQaRfLPkdbMiT+YI/7kdCzMxSeywsu8KhlU3A6f1SswOm2vZb74fXh/OFilQ83jHko5AsJ/YqChqzJyanq6f9kDciZXO3PxV+q11Jvx0fYwhRCI/qsWgyLUYWWhZQB/ni9iBFQM89W540fSIxJukHl8TtSk2qI5q9L4NdbKUyqaDQwu4TpmHW53VdHkLF+S/7VVR7MJvI+leoDBUxLs66JMHGSNhmC2lpOpeO9axTzZDY5UjLAbOlPHtThzne+Xq17Rcl+kdkdJtKRcPE4RF7PWK+5Ye8Pbias/8DU13tUfJq/BhLTmYNKpZRf+1eURSKygL1TvP1abhUarxs31JEUI47iF1/slRi2K1GbmVc0v7VQKvLKBB5MsPUf8zno1delEE/7WTLtzVvwSR4lai/vMVt/SuQXi/Va3XgRb3tAltsx1B1UXrzUfEeA2ph8WE5KQv3Xrjwk2In5A/ZMHAt
    username: AgC9rhD8dUpRzyFf9HVsG5IJq+6yn1KgMDARmYAVgWyyD0jCunEGpwr3A+xSila9DXdOASj50hF4JMVc98P87YU/D2p+R9W8wMNsPMDz/Y9sn68P96jRweLqtk+/qKgbSe5rry06yRAC6Crc5u2hVlceVi1T+zpxZRbtVnhFbG+dPNyzoZr1ZrmWfNC1V88r3DFBgC5qV8xC/qDoT9NzWHrcu5/463wQOv3JNnZklm/5Jh7zIy/BKGbc37bJocTYeZScUHuRdfMMkDsABJMWECr+DRSouSJ0pXeYyEXAJdkS4NoFY8YY880DOAr4+Z2OENqUlALR9qEyfZVNy/mp4S0c0GitEExAy4t5kPkuxx5uOr0VHcF9QYkxpH+K8T8/1RlDSuUqB9N1xkl+JFpYu74DlAApQ+n/W2dT+tW2BkNeF4CrGS35arPGw2cY2pn5O8C60sZR7b31NVsIJF4wk7x0vkwvgcvJgKvhw5sQHKv7vNtfZUVCp/FZtsAle7lioUWnvqh3JAz85IvqJVn6cvEEpI0pKuM74DJ9DWCXjG1dZchiv1jABe9ncC8Dv86aK/+o8oyEb/SaY33Wg6adQXUjNBb5+YFyDLseCL6Va5GyP6DmBgZZZ1dF0Aih4TfDn4y1q2FQcZ8erJJYVk2E9/cGr7mbRHKSO0eLuYizYAg7nl1CB25HV19bRWZnR4dU0rgeMvAoahG9Kxc=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
