---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    password: AgBVTMppO8zrdt+hTTGZN871NHnw5E7lRF5RM+7Pv9+i3gGJ77KKBiGLsenyzFlnjNXWmkW5QosQ0zjbFVtit7CtV3iSCK4XpMudr1LTY6iJuwBSfKW33Oc8bjgrd/3QnW9DSfvIdD1rgO/zTzXJTCL8KIS1+i2TSnu+yVEo9j0IrOwh2VkrYeh7Fxf0kvB0V08aKy8YkXofjFojQKPx3V5Cm0rLHogrziopJNRjF+poPEwVAGkD3T9N28M/xkUQt/MsbdXtn5SzVX1REe0Ya+Xh65TJ0tyDM133xNSqcOY0TxOVE4mOGDo9eFhzWg4mljEAlF5mUk19PBEL56CRCIuSzNM1J8FfrrC6V/1xud/a9za1PKGbYTELzyqsKNnM+6RGyrrNHr8V68ClMuZjjBHmAGPXA/zMQ6g3MmB6xCOKLOPQHReoyJwCsynQrdbdv1aCkRB+gURR5kHVo+Ghm9n2KPOOGzVQXyM5HuTPz4xq3AZlRekPYVQFG1mM4PEUGesVz/Hp67r8rEbSG2FWSmSjummvCMNPldzhBiYo84ODMsKqxhTiO5DRONbtKTz6ezrdu7u6zzww6tHsEQht+icdFpwVXmoNsZhosAq/7K2YHLGJqeGTpvfgb3Qmr1w91+PJ/8U0vRzGsTmBqLlrQrpRW/UzZqolHTW1ZHJnw99iUu83iYWYtmu10WTQs0Hj2eTaVs3fHseoPia5AesfrYGfwkbQszo+Nn0Gyt7vqD3+Ky1zA4TjS/ER
    username: AgAjob5vnXJuMa09nwCFf0SAhqNzTbyWMWJDfqcRkabgS9lpxWmfPJIv5fpDHKgDcDSRGhjol4SOunP6DXbE1kY49gvJUzCLT404mk2fpiOzcSLKF+5ZXNsaUH1Lb3zT/8lesYobsnAnTM9iHOxq2cYD5VJwzvHE24F0kT/S2sA7QD4S0gsijaxS5DCKW/LMXfybzvWx8uDWtnBnGiWxtXGOlCDX8+Br4VHcNV8o4X3d20/9fV5gcC+yU5nq0q++GcuTnBmeC8XtDhWOpfhpl/iCpP8q85ExVnfoIdQ9lH7cOTaaecVR5FnCEpn7ghrcIjxRUAiFXfgU7A259/DNgA7f+lORogTHuuNDDuOh/xlI2cSurVJIhPC7DoNqzJYdV/h5DUqp8+E0seej79bbmxKjnm0vYvSCGvoBIp2czog4rcUW/ohd4iIXCnrh5pohWaK22Xjf4fJwdnt0jNtxFu6afDY7kHfisqzWzJJSJMmpmWwO2jJmoo8F6F52ap9HM5yfjIlQJN8QuldjMHoWOglrWXURRTmiILzh6ENny12wRXBIdmvIzYTsGDy9MnPE+j5ofijoNDKdGhQIS7ttGb7N03WwrFhTW9E22/jY3PyEFEfHXsBFrTdsBveOdcHJPu4wLloR/ufk39IoGUmEAMWryoJMHBEi0mS2CgUXioeHDiKkxABY4NOnwOEVzdrtSnMrX55nXLAFUUE=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
