# apiVersion: argoproj.io/v1alpha1
# kind: Sensor
# metadata:
#   name: webhook
# spec:
#   template:
#     serviceAccountName: argo-events-sa
#   dependencies:
#     - name: test-dep
#       eventSourceName: webhook
#       eventName: example
#   triggers:
#     - template:
#         name: webhook-workflow-trigger
#         k8s:
#           operation: create
#           source:
#             resource:
#               apiVersion: argoproj.io/v1alpha1
#               kind: Workflow
#               metadata:
#                 generateName: webhook-
#                 namespace: argo
#               spec:
#                 entrypoint: whalesay
#                 arguments:
#                   parameters:
#                   - name: message
#                     # the value will get overridden by event payload from test-dep
#                     value: hello world
#                 templates:
#                 - name: whalesay
#                   inputs:
#                     parameters:
#                     - name: message
#                   container:
#                     image: docker/whalesay:latest
#                     command: [cowsay]
#                     args: ["{{inputs.parameters.message}}"]
#           parameters:
#             - src:
#                 dependencyName: test-dep
#                 dataKey: body
#               dest: spec.arguments.parameters.0.value


apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: ci-cd-workflow-trigger
        k8s:
          # group: argoproj.io
          # version: v1alpha1
          # operation: submit
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-cd-
                namespace: argo
              spec:
                entrypoint: build
                workflowTemplateRef:
                  name: ci-cd-template
                  clusterScope: true
                # templates:
                # - name: build
                #   dag:
                #     tasks:
                #     - name: build
                #       template: build-template
                #       arguments:
                #         parameters:
                #         - name: step
                #           value: BUILD
                # - name: build-template
                #   inputs:
                #     parameters:
                #     - name: step
                #   container:
                #     image: docker/whalesay:latest
                #     command: [cowsay]
                #     args: ["{{inputs.parameters.step}}"]