apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juice-shop-staging
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Add labels to your application object.
  labels:
    name: juice-shop-app
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/image-list: juice-shop=iurimihai/juice-shop
    argocd-image-updater.argoproj.io/juice-shop.allow-tags: regexp:test-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/juice-shop.update-strategy: latest
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/iurimihai/juice-shop-deployment.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: main  # For Helm, this refers to the chart version.
    path: staging

  destination:
    server: https://kubernetes.default.svc
    namespace: juice-shop-test

    # # kustomize specific config
    # kustomize:
    #   # Optional kustomize version. Note: version must be configured in argocd-cm ConfigMap
    #   version: v3.5.4
    #   # Supported kustomize transformers. https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
    #   namePrefix: prod-
    #   nameSuffix: -some-suffix
    #   commonLabels:
    #     foo: bar
    #   commonAnnotations:
    #     beep: boop
    #   images:
    #   - gcr.io/heptio-images/ks-guestbook-demo:0.2
    #   - my-app=gcr.io/my-repo/my-app:0.1

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      prune: true
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    
    # The retry feature is available since v1.7
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
