apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.3/controller.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["--key-renew-period=0"]
  target:
    group: apps
    version: v1
    kind: Deployment
    name: sealed-secrets-controller
