apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- argocd-install.yaml
- image-updater-install.yaml

patches:
- path: patches/argocd-cm.yaml
- path: patches/argocd-image-updater.yaml
