apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- argocd-install.yaml
- image-updater-install.yaml
- ingress.yaml
- resolv-cm.yaml
- github-access-sealed.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.1/manifests/install.yaml
# - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml

patches:
- path: patches/argocd-cm.yaml
- path: patches/argocd-image-updater.yaml
