apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  # - rbac.yaml
  - namespace.yaml
  - workflowtemplates/say-hello-template.yaml
  - workflowtemplates/say-hello-workflow.yaml
  - install.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["server", "--auth-mode=server"]
  target:
    group: apps
    version: v1
    kind: Deployment
    name: argo-server
# - path: workflow-controller-configmap.yaml
#   target:
#     group: ""
#     version: v1
#     kind: ConfigMap
#     name: workflow-controller-configmap
